# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import proto.voting_pb2 as voting__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binner.proto\x12\x0cvoting.inner\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cvoting.proto\"\x19\n\x17\x45lectionRecoveryRequest\"$\n\x05Voter\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05group\x18\x02 \x02(\t\"V\n\x04Vote\x12\x15\n\relection_name\x18\x01 \x02(\t\x12\x13\n\x0b\x63hoice_name\x18\x02 \x02(\t\x12\"\n\x05voter\x18\x03 \x02(\x0b\x32\x13.voting.inner.Voter\"B\n\x0e\x45lectionResult\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12 \n\x05\x63ount\x18\x02 \x03(\x0b\x32\x11.voting.VoteCount\"\x9f\x01\n\x0e\x45lectionStatus\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06groups\x18\x02 \x03(\t\x12\x0f\n\x07\x63hoices\x18\x03 \x03(\t\x12 \n\x05\x63ount\x18\x04 \x03(\x0b\x32\x11.voting.VoteCount\x12\x0e\n\x06voters\x18\x05 \x03(\t\x12,\n\x08\x65nd_date\x18\x06 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\"<\n\tElections\x12/\n\telections\x18\x01 \x03(\x0b\x32\x1c.voting.inner.ElectionStatus2\x83\x02\n\x0e\x65VotingReplica\x12\x32\n\x0e\x43reateElection\x12\x10.voting.Election\x1a\x0e.voting.Status\x12.\n\x08\x43\x61stVote\x12\x12.voting.inner.Vote\x1a\x0e.voting.Status\x12\x39\n\tGetResult\x12\x14.voting.ElectionName\x1a\x16.voting.ElectionResult\x12R\n\x10\x45lectionRecovery\x12%.voting.inner.ElectionRecoveryRequest\x1a\x17.voting.inner.Elections')



_ELECTIONRECOVERYREQUEST = DESCRIPTOR.message_types_by_name['ElectionRecoveryRequest']
_VOTER = DESCRIPTOR.message_types_by_name['Voter']
_VOTE = DESCRIPTOR.message_types_by_name['Vote']
_ELECTIONRESULT = DESCRIPTOR.message_types_by_name['ElectionResult']
_ELECTIONSTATUS = DESCRIPTOR.message_types_by_name['ElectionStatus']
_ELECTIONS = DESCRIPTOR.message_types_by_name['Elections']
ElectionRecoveryRequest = _reflection.GeneratedProtocolMessageType('ElectionRecoveryRequest', (_message.Message,), {
  'DESCRIPTOR' : _ELECTIONRECOVERYREQUEST,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:voting.inner.ElectionRecoveryRequest)
  })
_sym_db.RegisterMessage(ElectionRecoveryRequest)

Voter = _reflection.GeneratedProtocolMessageType('Voter', (_message.Message,), {
  'DESCRIPTOR' : _VOTER,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:voting.inner.Voter)
  })
_sym_db.RegisterMessage(Voter)

Vote = _reflection.GeneratedProtocolMessageType('Vote', (_message.Message,), {
  'DESCRIPTOR' : _VOTE,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:voting.inner.Vote)
  })
_sym_db.RegisterMessage(Vote)

ElectionResult = _reflection.GeneratedProtocolMessageType('ElectionResult', (_message.Message,), {
  'DESCRIPTOR' : _ELECTIONRESULT,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:voting.inner.ElectionResult)
  })
_sym_db.RegisterMessage(ElectionResult)

ElectionStatus = _reflection.GeneratedProtocolMessageType('ElectionStatus', (_message.Message,), {
  'DESCRIPTOR' : _ELECTIONSTATUS,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:voting.inner.ElectionStatus)
  })
_sym_db.RegisterMessage(ElectionStatus)

Elections = _reflection.GeneratedProtocolMessageType('Elections', (_message.Message,), {
  'DESCRIPTOR' : _ELECTIONS,
  '__module__' : 'inner_pb2'
  # @@protoc_insertion_point(class_scope:voting.inner.Elections)
  })
_sym_db.RegisterMessage(Elections)

_EVOTINGREPLICA = DESCRIPTOR.services_by_name['eVotingReplica']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELECTIONRECOVERYREQUEST._serialized_start=76
  _ELECTIONRECOVERYREQUEST._serialized_end=101
  _VOTER._serialized_start=103
  _VOTER._serialized_end=139
  _VOTE._serialized_start=141
  _VOTE._serialized_end=227
  _ELECTIONRESULT._serialized_start=229
  _ELECTIONRESULT._serialized_end=295
  _ELECTIONSTATUS._serialized_start=298
  _ELECTIONSTATUS._serialized_end=457
  _ELECTIONS._serialized_start=459
  _ELECTIONS._serialized_end=519
  _EVOTINGREPLICA._serialized_start=522
  _EVOTINGREPLICA._serialized_end=781
# @@protoc_insertion_point(module_scope)
